### ISSUE TITLE
Partage à la commu : iOs shortcut "SMS Somfy vers HA"

### ISSUE THREAD

**Issue by Pr20100** [the8tre/somfy-protexial#70]
Salut à tous,

je vous partage ici un raccourci iOS qui permet de renvoyer le contenu des SMS de l'alarme vers Home Assistant : **[Lien iCloud]( https://www.icloud.com/shortcuts/3b08427787e542479f3417aceae0c014)**

L'ensemble des explications pour la configuration sont contenues dans le raccourci sous forme de commentaires afin de vous simplifier la tâche.

### Fonctions:
- Récupère et modifie le contenu SMS afin de le raccourcir et améliorer la lisibilité
- Copie du résultat dans une entité input_text sous HA pour l'utiliser dans vos automatisations, l'afficher sur un Dashboard...
- Alerte supplémentaire en cas de déclenchement de l'alarme sur votre téléphone

### Exemple de notification simple sous HA:

```
description: Notification SMS alarme
mode: single
triggers:
  - trigger: state
    entity_id:
      - input_text.sms_alarme
    from: null
    to: null
conditions: #pour ne pas être notifié si le message sms est vide
  - condition: not
    conditions:
      - condition: state
        entity_id: input_text.sms_alarme
        state: ""
actions:
  - action: notify.telegram_bot #remplacer par votre service de notification
    metadata: {}
    data:
      title: Alarme
      message: {{ trigger.to_state.state }} #pour afficher le message reçu
```

N'hésitez pas à faire un retour si vous testez et amusez-vous bien!
